#!/bin/bash

#TODO: check if is root

PREFIX="/etc/my-signed-boot"

cat /boot/*-ucode.img /boot/initramfs-linux.img > /tmp/initramfs-linux.img.tmp

objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="/etc/my-signed-boot/kernel-command-line.txt" --change-section-vma .cmdline=0x30000 \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" --change-section-vma .splash=0x40000 \
    --add-section .linux="/boot/vmlinuz-linux" --change-section-vma .linux=0x2000000 \
    --add-section .initrd="/tmp/initramfs-linux.img.tmp" --change-section-vma .initrd=0x3000000 \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/boot/vmlinuz-linux.efi"

rm /tmp/initramfs-linux.img.tmp
cat /boot/*-ucode.img /boot/initramfs-linux-fallback.img > /tmp/initramfs-linux-fallback.img.tmp

objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="/etc/my-signed-boot/kernel-command-line.txt" --change-section-vma .cmdline=0x30000 \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" --change-section-vma .splash=0x40000 \
    --add-section .linux="/boot/vmlinuz-linux" --change-section-vma .linux=0x2000000 \
    --add-section .initrd="/tmp/initramfs-linux-fallback.img.tmp" --change-section-vma .initrd=0x3000000 \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/boot/vmlinuz-linux-fallback.efi"

rm /tmp/initramfs-linux-fallback.img.tmp

sbsign --key ${PREFIX}/DB.key --cert ${PREFIX}/DB.crt --output /boot/vmlinuz-linux.efi /boot/vmlinuz-linux.efi
sbsign --key ${PREFIX}/DB.key --cert ${PREFIX}/DB.crt --output /boot/vmlinuz-linux-fallback.efi /boot/vmlinuz-linux-fallback.efi

echo ""
echo "Add the stub to the EFI manually with: "
echo "sudo efibootmgr --disk /dev/nvme0n1 --part 1 --create --label \"Arch Linux\" --loader /vmlinuz-linux.efi"
echo "sudo efibootmgr --disk /dev/nvme0n1 --part 1 --create --label \"Arch Linux Fallback\" --loader /vmlinuz-linux-fallback.efi"
echo ""